# Optional module: Fronius Wattpilot EV control (opt-in)
# Enable by turning on: input_boolean.ems_ev_enabled
# Requires a Wattpilot entity for max charging current. Default expected:
#   number.wattpilot_max_charging_current
# If your entity has a different id, rename it in Home Assistant (Settings → Devices & Services → Entities).
#
# This module:
# - Binds EMS helper input_number.ems_ev_max_charging_current → Wattpilot max current
# - Starts/stops EV charging during nightprice and protects fuses via phase current limits
#

- alias: "EMS EV: bind max current helper → Wattpilot"
  id: ems_ev_bind_max_current
  mode: restart
  trigger:
    - platform: state
      entity_id: input_number.ems_ev_max_charging_current
  condition:
    - condition: state
      entity_id: input_boolean.ems_ev_enabled
      state: "on"
  action:
    - choose:
        - conditions: >
            { states('number.wattpilot_max_charging_current') not in ['unknown','unavailable','none',''] }
          sequence:
            - service: number.set_value
              target:
                entity_id: number.wattpilot_max_charging_current
              data:
                value: "{ states('input_number.ems_ev_max_charging_current') | float(0) }"

- alias: "EMS EV: start EV charging on nightprice"
  id: ems_ev_start_on_nightprice
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.electricity_nightprice_active
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.ems_ev_enabled
      state: "on"
  action:
    - choose:
        - conditions: >
            { states('number.wattpilot_max_charging_current') not in ['unknown','unavailable','none',''] }
          sequence:
            - service: number.set_value
              target:
                entity_id: number.wattpilot_max_charging_current
              data:
                value: "{ states('input_number.ems_ev_max_charging_current') | float(0) }"
    # If Wattpilot entities exist for on/off, user can add them here; max current alone is safe.
    # Many installs start charging automatically when current > 0.

- alias: "EMS EV: night safety governor (phase current / import cap)"
  id: ems_ev_night_safety_governor
  mode: restart
  trigger:
    - platform: time_pattern
      seconds: "/10"
    - platform: state
      entity_id:
        - sensor.ems_grid_power_w
        - sensor.ems_grid_current_l1
        - sensor.ems_grid_current_l2
        - sensor.ems_grid_current_l3
        - input_number.cap_night_max_power_w
        - input_number.cap_night_max_phase_a
        - input_boolean.ems_ev_enabled
        - binary_sensor.electricity_nightprice_active
  condition:
    - condition: state
      entity_id: binary_sensor.electricity_nightprice_active
      state: "on"
    - condition: state
      entity_id: input_boolean.ems_ev_enabled
      state: "on"
  action:
    - variables:
        p_grid: "{ states('sensor.ems_grid_power_w') | float(0) }"
        p_max: "{ states('input_number.cap_night_max_power_w') | float(0) }"
        i_max: "{ states('input_number.cap_night_max_phase_a') | float(0) }"
        i1: "{ states('sensor.ems_grid_current_l1') | float(none) }"
        i2: "{ states('sensor.ems_grid_current_l2') | float(none) }"
        i3: "{ states('sensor.ems_grid_current_l3') | float(none) }"
        any_over: >
          { (i1 is not none and i1 > i_max)
              or (i2 is not none and i2 > i_max)
              or (i3 is not none and i3 > i_max) }
    - choose:
        - conditions: "{ p_grid > p_max or any_over }"
          sequence:
            # Drop EV current to minimum (6A) to relieve fuses/import. You can also set 0 if you prefer.
            - choose:
                - conditions: >
                    { states('number.wattpilot_max_charging_current') not in ['unknown','unavailable','none',''] }
                  sequence:
                    - service: number.set_value
                      target:
                        entity_id: number.wattpilot_max_charging_current
                      data:
                        value: 6
