- alias: "EMS: decide night charging when nightprice starts"
  id: ems_decide_night_charging
  mode: single
  triggers:
    - trigger: state
      entity_id: input_boolean.cap_nightprice_active
      to: "on"
  actions:
    - variables:
        soc: "{{ states('sensor.ems_battery_soc') | float(0) }}"
        start_pct: "{{ states('input_number.cap_night_soc_start_pct') | float(0) }}"
        never_charge: "{{ is_state('input_boolean.cap_night_never_charge', 'on') }}"
    - choose:
        - conditions: "{{ never_charge }}"
          sequence:
            - service: input_boolean.turn_off
              target: { entity_id: input_boolean.cap_night_charge_active }
            - service: script.battery_set_power_target
              data: { power_w: 0 }

        - conditions: "{{ soc < start_pct }}"
          sequence:
            - service: input_boolean.turn_on
              target: { entity_id: input_boolean.cap_night_charge_active }

      default:
        - service: input_boolean.turn_off
          target: { entity_id: input_boolean.cap_night_charge_active }
        - service: script.battery_set_power_target
          data: { power_w: 0 }

- alias: "EMS: perform night charging when active"
  id: ems_perform_night_charging
  mode: restart
  triggers:
    - trigger: time_pattern
      seconds: "/30"
    - trigger: state
      entity_id:
        - sensor.ems_battery_soc
        - input_boolean.cap_nightprice_active
        - input_boolean.cap_night_charge_active
        - input_boolean.cap_night_never_charge
  conditions:
    - condition: state
      entity_id: input_boolean.cap_nightprice_active
      state: "on"
    - condition: state
      entity_id: input_boolean.cap_night_charge_active
      state: "on"
    - condition: state
      entity_id: input_boolean.cap_night_never_charge
      state: "off"
  actions:
    - variables:
        soc: "{{ states('sensor.ems_battery_soc') | float(0) }}"
        target_pct: "{{ states('input_number.cap_night_soc_target_pct') | float(0) }}"
        charge_power: "{{ states('input_number.cap_night_charge_power_w') | float(0) }}"
    - choose:
        - conditions: "{{ soc < target_pct }}"
          sequence:
            - service: script.battery_set_power_target
              data:
                power_w: "{{ (0 - charge_power) | int }}"
        - conditions: "{{ soc >= target_pct }}"
          sequence:
            - service: script.battery_set_power_target
              data: { power_w: 0 }
            - service: input_boolean.turn_off
              target: { entity_id: input_boolean.cap_night_charge_active }

- alias: "EMS: dayprice start actions (nightprice ends)"
  id: ems_dayprice_start_reset
  mode: single
  triggers:
    - trigger: state
      entity_id: input_boolean.cap_nightprice_active
      to: "off"
  actions:
    - service: script.battery_set_power_target
      data: { power_w: 0 }
    - service: input_boolean.turn_off
      target: { entity_id: input_boolean.cap_night_charge_active }
    - service: script.battery_reset_charging_5_int

- alias: "EMS: night safety (max grid import & phase current)"
  id: ems_night_safety_limits
  mode: restart
  triggers:
    - trigger: time_pattern
      seconds: "/10"
  conditions:
    - condition: state
      entity_id: input_boolean.cap_nightprice_active
      state: "on"
  actions:
    - variables:
        p_grid: "{{ states('sensor.ems_grid_power') | float(0) }}"
        p_max: "{{ states('input_number.cap_night_max_power_w') | float(0) }}"
        i_max: "{{ states('input_number.cap_night_max_phase_a') | float(0) }}"
        i1: "{{ states('sensor.ems_grid_current_l1') | float(none) }}"
        i2: "{{ states('sensor.ems_grid_current_l2') | float(none) }}"
        i3: "{{ states('sensor.ems_grid_current_l3') | float(none) }}"
        any_over: >
          {{ (i1 is not none and i1 > i_max)
              or (i2 is not none and i2 > i_max)
              or (i3 is not none and i3 > i_max) }}
    - choose:
        - conditions: >
            {{ p_grid > p_max or any_over }}
          sequence:
            - service: script.battery_set_power_target
              data: { power_w: 0 }
