- alias: "Tariff: Update nightprice/dayprice based on schedule"
  id: tariff_schedule_controller
  mode: restart
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id:
        - input_select.tariff_mode
        - input_datetime.tariff_day_start
        - input_datetime.tariff_day_end

  action:
    - variables:
        mode: "{{ states('input_select.tariff_mode') }}"
        s: "{{ states('input_datetime.tariff_day_start') }}"
        e: "{{ states('input_datetime.tariff_day_end') }}"

        now_ts: "{{ as_timestamp(now()) }}"

        start_ts: >-
          {% if s in ['unknown','unavailable','none','None',''] %}
            {{ none }}
          {% else %}
            {{ as_timestamp(today_at(s)) }}
          {% endif %}

        end_ts: >-
          {% if e in ['unknown','unavailable','none','None',''] %}
            {{ none }}
          {% else %}
            {{ as_timestamp(today_at(e)) }}
          {% endif %}

        is_day: >-
          {% if mode == 'Force dayprice' %}
            true
          {% elif mode == 'Force nightprice' %}
            false
          {% elif start_ts is none or end_ts is none %}
            false
          {% else %}
            {% if start_ts < end_ts %}
              {{ now_ts >= start_ts and now_ts < end_ts }}
            {% else %}
              {# Wrap midnight #}
              {{ now_ts >= start_ts or now_ts < end_ts }}
            {% endif %}
          {% endif %}

        is_nightprice: "{{ not is_day }}"

    - choose:
        - conditions: "{{ is_nightprice and is_state('input_boolean.cap_nightprice_active', 'off') }}"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.cap_nightprice_active

        - conditions: "{{ (not is_nightprice) and is_state('input_boolean.cap_nightprice_active', 'on') }}"
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.cap_nightprice_active
